dbs:
  - path: /dev/fly_vol/juicefs.db
    replicas:
      - type: s3
        endpoint: $S3_ENDPOINT
        bucket: $BUCKET_NAME
        region: $S3_REGION
        access-key-id: $S3_ACCESS_KEY
        secret-access-key: $S3_SECRET_KEY

logging:
  level: warn

addr: "0.0.0.0:9090"

