app = "kurt-juicefs"
primary_region = "atl"
kill_signal = "SIGINT"
kill_timeout = 30

[experimental]
machine_config = "./machine-config.json"

[build]
image = "docker.io/library/alpine:latest"

[[vm]]
  cpu_kind = "performance"
  cpus = 4
  memory_mb = 8192

[[mounts]]
  source = "juicefs_data"
  destination = "/dev/fly_vol"
